In [1]:
import numpy as np

In [12]:
#-----------TO RESHAPE AN ARRAY FROM 1D TO 2D------------#

# recall np.arange is like a for loop np.arrange(1,31) means array of integers from 1 to 30
arr = np.arange(1,31) 
print(f"{arr}\n")

# recall linspace is start to end with how much numbers to include with equal linear spacing between start and end
arr1 = np.linspace(1,10,10)
print(f"{arr1}\n")

arr = arr.reshape(5,6)
print(f"{arr}\n")

arr1 = arr1.reshape(5,2)
print(f"{arr1}\n")

arr1 = arr1.reshape(2,5)
print(f"{arr1}\n")

arr1 = arr1.reshape(10,1)
print(arr1)

# NOTE WHILE RESHAPING ELEMENT COUNT MUST BE SAME IN ORIGINAL AND RESHAPED ARRAY 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]
 [ 9. 10.]]

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]

[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]]
