In [1]:
import numpy as np

In [12]:
#-----------MATRIX MULTIPLICATION--------------#


arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
print(f" {arr1} \n\n {arr2}")


 [[1 2]
 [3 4]] 

 [[5 6]
 [7 8]]


In [19]:

print("\n Multiplication Based on simple indexing ") 
print(arr1*arr2)


print("\n Multiplication Based on Row-Column method indexing ") 

print(arr1@arr2)
print("\n")
print(np.dot(arr1, arr2))

# np.dot(arr1,arr2) and arr1@arr2 


 Multiplication Based on simple indexing 
[[ 5 12]
 [21 32]]

 Multiplication Based on Row-Column method indexing 
[[19 22]
 [43 50]]


[[19 22]
 [43 50]]


In [21]:
#-------------MATRIX TRANSPOSE---------#

print(arr1.T)
print(arr2.T)

[[1 3]
 [2 4]]
[[5 7]
 [6 8]]
