In [1]:
import numpy as np

In [2]:

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],  # Student 1
    [19, 92, 88],  # Student 2
    [17, 76, 95],  # Student 3
    [18, 65, 70],  # Student 4
    [20, 90, 85]   # Student 5
])


In [3]:
# Find the shape of matrix
shape = data.shape
print(shape)

print("Rows : ", shape[0])
print("Columns : ", shape[1])

(5, 3)
Rows :  5
Columns :  3


In [4]:
# Find the Average age of students

age_columns = data[0:5,0:1]
print("Age: \n" ,age_columns)
print("\nMean: ", np.mean(age_columns))


Age: 
 [[18]
 [19]
 [17]
 [18]
 [20]]

Mean:  18.4


In [5]:
# Extract Math marks of all students ..

math_marks = data[:,1]
math_marks_2d = data[:,1:2]
print(math_marks)
print(math_marks_2d)

[85 92 76 65 90]
[[85]
 [92]
 [76]
 [65]
 [90]]


In [6]:
# Extract Avg and Std deviation of Science marks 

sci_marks = data[0:6,2]
print(sci_marks)
print("\n")

mean_sci = np.mean(sci_marks)
print("Mean Science: " , mean_sci)

std_dev_sci = np.std(sci_marks)
print("Std Deviation Science: " , std_dev_sci)

var_sci = np.var(sci_marks)
print("Variance Science: " , var_sci)

print("\nMean [Age , Maths , Science] : ", np.mean(data,axis=0))
print("\nStd Dev [Age , Maths , Science] : ", np.std(data,axis=0))
print("\nVariance [Age , Maths , Science] : ", np.var(data,axis=0))

[78 88 95 70 85]


Mean Science:  83.2
Std Deviation Science:  8.565045242145542
Variance Science:  73.36

Mean [Age , Maths , Science] :  [18.4 81.6 83.2]

Std Dev [Age , Maths , Science] :  [1.0198039  9.97196069 8.56504524]

Variance [Age , Maths , Science] :  [ 1.04 99.44 73.36]


In [7]:
# Find the highest Maths Science marks

sci_marks = data[:,2]
maths_marks = data[:,1]

print("Max Marks -> [Maths , Science] " , np.max(sci_marks) , np.max(maths_marks))


Max Marks -> [Maths , Science]  95 92


In [8]:
# Get details of students who scored more than 90 marks in Math

math_marks =data[:,1]
print(math_marks>90)
print(data[math_marks>90])

[False  True False False False]
[[19 92 88]]


In [9]:
# Increase Math marks of all students by 5

math_marks =data[:,1]
print(data[:,1]+5)
print("\n")
print(data) 

# here data didnt change as we did calculation using data not assigned new values .
# But numpy changing sliced array changes the original array but here we did calculation not actually changes the values 
# changing means assigning new values to an index means maths[1][1] = new_marks will change but doing any calculation
# or operation like data[:,1]+5 will allocate new temp memory for +5 maths marks and 
# delete it immediately after printing it , to assign a new value we must do data[:,1] = data[:,1] + 5

#----------------------

print("\n")
data[:, 1] = data[:, 1] + 5
print(data)

#----------------------

# To prove that slicing of numpy arrays creates a view we will change math_marks[0] to 99
# and check if original data changed 

math_marks[0] = 99
print("\n")
print(data)


[90 97 81 70 95]


[[18 85 78]
 [19 92 88]
 [17 76 95]
 [18 65 70]
 [20 90 85]]


[[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 70 70]
 [20 95 85]]


[[18 99 78]
 [19 97 88]
 [17 81 95]
 [18 70 70]
 [20 95 85]]


In [10]:
# Find How many students are younger than 19

bool_age = data[:,0]<19
print(data[bool_age])
print("Count  : " , np.shape(data[bool_age]))
print("Count of students : ", len(data[bool_age]))


[[18 99 78]
 [17 81 95]
 [18 70 70]]
Count  :  (3, 3)
Count of students :  3


In [11]:
# Get data of students who scored at least 80 in both subjects

bool_marks_req_data = (data[:,1]>80) & (data[:,2]>80)
print(data[bool_marks_req_data])

[[19 97 88]
 [17 81 95]
 [20 95 85]]


In [12]:
 # Replace all science with <75 with 0
print(data)
print("\n")

print(data[:,2])
sci_less_75 = data[:,2]<75
print(sci_less_75)
print("\n")
print(data[sci_less_75])

print("\n")
data[data[:, 2] < 75, 2] = 0
print(data)



[[18 99 78]
 [19 97 88]
 [17 81 95]
 [18 70 70]
 [20 95 85]]


[78 88 95 70 85]
[False False False  True False]


[[18 70 70]]


[[18 99 78]
 [19 97 88]
 [17 81 95]
 [18 70  0]
 [20 95 85]]
